/**:
  ros__parameters:
    #for odom
    odom/sendTF: false
    #topic names 
    odom/lidar_topic: 
    odom/imu_topic: /imu/data2 #/imu_correct
    odom/lidar_type:  # livox velodyne ouster

    #frames
    odom/odom_frame: lio_odom
    odom/robot_frame: base_link
    odom/imu_frame: imu_link
    odom/lidar_frame: 
    odom/min_radius: 
    odom/max_radius: 
    odom/point_filter_num: 6
    odom/time_scale: 1.0 # nclt: 0.001 other: 1000.0
    odom/enable_ahrs_initalization: false
    odom/enable_acc_correct: false

    odom/scan_resolution: 0.2
    odom/voxel_map_resolution: 0.5
    odom/max_iterations: 10

    odom/acc_cov: 0.1
    odom/gyr_cov: 0.1
    odom/ba_cov: 0.000001
    odom/bg_cov: 0.000001
    odom/init_ori_cov: 0.0001
    odom/init_pos_cov: 0.0001
    odom/init_vel_cov: 100.0
    odom/init_ba_cov: 0.0001
    odom/init_bg_cov: 0.0001
    odom/gravity: 9.80665

    odom/keyframe_leafsize: 0.08

    odom/gicp_constraints_gain: 100.0
    odom/point2plane_constraints_gain: 1000.0
    odom/enable_undistort: true
    odom/enable_outlier_rejection: true

    

    
    #for extrinsics
    extrinsics/imu2lidar/t: [0.0, 0.0, 0.0]
    extrinsics/imu2lidar/r: [1.0, 0.0, 0.0,
                            0.0, 1.0, 0.0,
                            0.0,  0.0, 1.0 ]
    
    extrinsics/robot2lidar/t: [0.0, 0.0, 0.0]
    extrinsics/robot2lidar/r: [1.0, 0.0, 0.0,
                              0.0, 1.0, 0.0,
                              0.0,  0.0, 1.0 ]
                              
    extrinsics/robot2imu/t: [0.0, 0.0, 0.0]
    extrinsics/robot2imu/r: [1.0, 0.0, 0.0,
                            0.0, 1.0, 0.0,
                            0.0,  0.0, 1.0 ]

    #for map
    # map/save_map_path: /home/agilex/humble_ws #do not put / at the end of line
    # map/map_name: jfe
    map/map_frame: map
    map/map_leafsize: 0.1


    ## for relocation
    reloc/max_translation_diff: 1.0
    reloc/max_rotation_diff: 0.1
    reloc/history_keyframe_fitness_score: 0.3

